name: ESLint

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: start ESLint
        run: |
          make install
          make publish
          make lint
        env:
          CI: true
